### ISSUE TITLE
If BeansHTML-API-VHG is enabled, Customizer breaks

### ISSUE THREAD

**Issue by n8finch** [JeffCleverley/Beans-Visual-Hook-Guide#1]
Hey Jeff! 

Love the plugin so far. Just noticed that if the plugin is enabled and I got to the customizer (to add a logo, Site Identity, etc.) it breaks. 

Not a big deal, I just disabled it and go along my merry way, but just wanted to let you know. 

Here's a screenshot: http://prntscr.com/im597s

Cheers,
Nate

**Comment by JeffCleverley** [comment]
Hey Nate! 

Yup confirmed that. The Customizer doesn't feature the admin toolbar at all, so throwing this error. 

Woohooo my first bug!!! I am beside myself with excitement! I'll get right on it.

Thanks for the catch.

Jeff

**Comment by JeffCleverley** [comment]
Added a return early clause before hooking in those actions.

```
if ( is_customize_preview() ) {
	    return;
    };
```

Should be good to go now.
