### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by paaljoachim** [JeffCleverley/Beans-Visual-Hook-Guide#7]
Hey Jeff

I installed and activated the plugin on a local Desktop Server site running PHP Version 5.5.24.
It showed these errors:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /Users/joachim/Documents/Websites/beans-tests.dev.cc/wp-content/plugins/Beans-Visual-Hook-Guide-master/src/markup/handler.php on line 14
--

1 | 0.0039 | 576160 | {main}( ) | ../plugins.php:0
2 | 0.3996 | 42013656 | plugin_sandbox_scrape( ) | ../plugins.php:172
3 | 0.3999 | 42032280 | include( '/Users/joachim/Documents/Websites/beans-tests.dev.cc/wp-content/plugins/Beans-Visual-Hook-Guide-master/beans-visual-hook-guide.php' ) | ../plugin.php:1897
4 | 0.3999 | 42035424 | LearningCurve\BeansVisualHookGuide\launch( ) | ../beans-visual-hook-guide.php:132
5 | 0.3999 | 42035424 | LearningCurve\BeansVisualHookGuide\autoload_files( ) | ../beans-visual-hook-guide.php:129

**Comment by paaljoachim** [comment]
Btw I uploaded a beans test site and in PHP version 5.6 and 7.0 it works fine. For whatever reason I am getting the above error using Desktop Server.

**Comment by JeffCleverley** [comment]
Oops forgot to close this after we discussed in the slack channel.

The plugin uses namespacing and requires php5.6+
